# Generated by Django 3.1.3 on 2020-11-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='aprodnome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='aprodqntd',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='aprodvalor',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='aprodativo',
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
