# Generated by Django 3.1.3 on 2020-11-16 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20201105_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acliente',
            fields=[
                ('acliid', models.AutoField(primary_key=True, serialize=False)),
                ('aclinome', models.CharField(max_length=255, verbose_name='Nome')),
                ('acliemail', models.CharField(max_length=255, verbose_name='Email')),
                ('aclipass', models.CharField(max_length=255, verbose_name='Senha')),
            ],
            options={
                'db_table': 'acliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apedido',
            fields=[
                ('apediid', models.AutoField(primary_key=True, serialize=False)),
                ('apedidata', models.DateField(auto_now_add=True)),
                ('apedistatus', models.SmallIntegerField(default=1)),
                ('apedivenc', models.DateField(default=datetime.datetime(2020, 11, 21, 19, 45, 35, 554308))),
            ],
            options={
                'db_table': 'apedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aproduto',
            fields=[
                ('aprodid', models.AutoField(primary_key=True, serialize=False)),
                ('aprodnome', models.CharField(max_length=255, verbose_name='Nome')),
                ('aprodvalor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('aprodqntd', models.IntegerField(verbose_name='Quantidade')),
                ('aprodativo', models.SmallIntegerField(verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Produto',
                'db_table': 'aproduto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aprodutoinstancia',
            fields=[
                ('aprinid', models.AutoField(primary_key=True, serialize=False)),
                ('aprinval', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprinqnt', models.IntegerField()),
            ],
            options={
                'db_table': 'aprodutoinstancia',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
